name: Lint, Validate and Test

on:
  push:
    branches:
      - main
    paths: '**.json'
  pull_request:
    branches:
      - main
    paths: '**.json'

jobs:
  json-validation:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Validate JSON
        uses: limitusus/json-syntax-check@v1
        with:
          pattern: "\\.json$"