name: Lint, Validate and Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  verify-json-validation:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Validate JSON
        uses: docker://orrosenblatt/validate-json-action:latest
        env:
          INPUT_SCHEMA: /config/schema.json
          INPUT_JSONS: /src/data/hounds.json