name: Lint, Validate and Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  json-validation:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Validate JSON
        uses: limitusus/json-syntax-check@v2
        with:
          pattern: "\\.json$"

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: npm
      - run: npm ci
      - name: Lint
        run: npm run lint
      - name: Test
        run: npm test
      - name: Build
        run: npm run build
